### ISSUE TITLE
Run prettier externally, only disable rules

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/eslint-config#34]
See https://github.com/Byndyusoft/sync-github-repos/blob/97c97921eab3c4760240cb9276a086c4ab90386a/.eslintrc.json#L45 as example

**Comment by litichevskiydv** [comment]
@Fun795 планирует до конца недели передать в ревью

**Comment by Fun795** [comment]
PR: https://github.com/Byndyusoft/eslint-config/pull/36
